### PR TITLE
Upgrade pear Mail libraries, use header charset for attachment filenames

### PR DESCRIPTION
**Pull request by greezybacon**
This includes upgrades to the Mail_Mime and Net_SMTP upstream libraries. It also includes a patch to use the defined header charset (`utf-8`) for attachment filename encoding

### CODE REVIEW

**Comment by matlinuxer2** [comment]
Thanks! I have applied this patch and tested it. All goes well, GJ!!

**Comment by infectormp** [comment]
Need bump osTicket PHP version to 5.4 because Net_SMTP v1.7.1 have Dependencies PHP Version: PHP 5.4.0 or newer.

or maybe better bump version to 5.5 or 5.6 because 5.4 not supported anymore
for 5.5 active support end at 10 July 2015, security support 10 July 2016
for 5.6 active support end at 28 Aug 2016, security support 28 Aug 2017

**Comment by greezybacon** [comment]
I agree that PHP 5.4 is a fair requirement for v1.10

**Comment by Chefkeks** [comment]
@greezybacon
When bumping the minimum requirement anyway, why not skip 5.4 and go to 5.5 or 5.6 in favor of the active/security support?

**Comment by greezybacon** [comment]
CentOS / RedHat 7 ship with PHP 5.4, and are still supported. Since that's the most current stable version of the popular server OS, I think we should support it. What versions are available with Windows Web Platform Installer?

**Comment by ntozier** [comment]
Web Platform Installer 5.0 lists the following options for PHP
5.6.0
5.5.11
5.4.24
5.3.28

**Comment by Chefkeks** [comment]
Ok makes sense to not skip PHP 5.4 since some distributions are still shipping with it as the default which I wasn't aware of. And as long as osTicket doesn't require any PHP 5.5 or 5.6 exclusive features/fixes I agree that 5.4 is a fair requirement.

**Comment by greezybacon** [comment]
As a side note, I would point out that we will be labelling a **requirement**. I think we should move our development testing and certification to PHP 5.6 and label that version as the *recommendation*.

**Comment by Chefkeks** [comment]
@greezybacon  :+1:

**Comment by greezybacon** [comment]
@protich was merging this a mistake? Doesn't it require PHP 5.4 for osTicket v1.9.x? Perhaps we should revert the changes to the PEAR libraries on the `develop` branch

**Pull request merged**
