### PR TITLE
v1.10 Fixes

### PR DESCRIPTION
**Pull request by protich**
PR for bug fixes... do not merge.

### CODE REVIEW

**Comment by Korrosivo** [comment]
Hi @protich, @greezybacon. I don't want to open a new issue and since GitHub has no PM's, I'm putting it here.

Tomorrow will be 8 months since v1.10 developer preview was launched. I've been following the development of this major version since then and ther are many new features, but no new releases.

Is develop-next so unstable as to release version 1.10-RC3? Stable enough for v.10-BETA? Is there a timeline or deadline for this release? I've seen many projects die for never stop adding new features to their main branch and I wouldn't want this to happen with osTicket.

You guys are incredible and osTickets is by far the best ticketing plataform in the market but please, keep in mind that most of us need to have in production stage a v1.XX version instead of a master.zip.

Thank you for your work!
:clap:

**Comment by ntozier** [comment]
Q: Is develop-next so unstable as to release version 1.10-RC3?
A: Last I heard they were planning a rc3.

Q: Stable enough for v.10-BETA?
A: RC's are betas.

**Comment by protich** [comment]
@Korrosivo - Thank you for the feedback! I can understand the frustration of waiting on a stable release for as long as it has been. We had every intention of keeping the rapid fire-releases, but we simply got overwhelmed internally due to some changes and priorities.

That said, v1.10 stable is planned before the end of __this month__ (you can quote me on it). We're doing last minute fixes and testing before we collapse ``develop-next`` to ``develop``. Our hosted platform is already running on v1.10 and we're confident it is stable enough for production use.

Going forward we'll get back to somewhat normalized release cycle, albeit in a little spaced-out cycles compared to releases in 2014-2015.

**Comment by Korrosivo** [comment]
@protich Thanks for your comment, glad to hear that v1.10 will be released soon :)

Again, thanks for your work.

**Comment by Chefkeks** [comment]
@protich
Great to hear that! Hope you release a RC3 prior to the final / stable 1.10 to get issue reports one more time before the new version is released ;)

**Comment by greezybacon** [comment]
Still looks good, @protich

**Comment by phillip159753** [comment]
Hi,

Firstly, Thank you for all the hard work that has been dedicated to maintaining this product. We have been using an OS Ticket implementation since 2011.

**In reference to a previous comment in this thread:**

_>That said, v1.10 stable is planned before the end of this month (you can quote me on it). We're doing last minute fixes and testing before we collapse develop-next to develop. Our hosted platform is already running on v1.10 and we're confident it is stable enough for production use.<_

Is it possible to receive an update on the timeline? 

Thanks!

Phillip Blythe
Georgia Softworks

**Comment by ntozier** [comment]
@phillip159753 when it ready it will be released.
There will as usual be an announcement.

**Comment by phillip159753** [comment]
Thank you for your informative response!

**Pull request merged**
