### PR TITLE
list: Fix add and edit for "Ticket Status" list

### LINKED ISSUE #2292: 1.10 RC1 Issues - Custom List Ticket Status
Unable to create new Status. The ajax window comes up but after saving the new status does not display anywhere in the system. If I go back to create the same one the system says that is already exists.

image
image

### PR DESCRIPTION
**Pull request by greezybacon**
This patch shores up the new list management feature with the custom list handler feature written to support lists being saved in a table other than %list_item, namely the built-in ticket status list.

Fixes #2292

### CODE REVIEW

**Comment by jdelhome3578** [comment]
Does not correct the issue, New Status still being saved in `list_items` instead of `ticket_status`

**Comment by jdelhome3578** [comment]
I am know able to open current Statuses but when creating a new status the `value` and settings do not save correctly.

**Comment by greezybacon** [comment]
@jdelhome3578 thanks for testing. I tried harder and submitted some updated code. Can you test again?

**Comment by jdelhome3578** [comment]
That look better!! Confirmed Fix!

**Comment by protich** [comment]
Reviewed-By: Peter Rotich <peter@enhancesoft.com>

**Pull request merged**
