### PR TITLE
oops: Fix ticket export to CSV

### PR DESCRIPTION
**Pull request by greezybacon**

### CODE REVIEW

**Comment by zulhiyatiuwi** [comment]
Excuse me... sorry to disturbing you...
I have trouble when i'm using osticketv-1.9.6. When i test it with open a new ticket, admin and departmen do not receive notification of new ticket on their email account. and also the user. the user is not get notification of ticket number. but the problem is show in osticket website.
could you help me with this problem, please???

**Comment by ntozier** [comment]
Your comment does not appear to have anything to do with this thread.
If you are having a problem I would invite you to post on the forums at http://osticket.com.
If you have a bug to report then I would recommend that you click on the New Issue button.
https://github.com/osTicket/osTicket-1.8/issues/new

**Comment by zulhiyatiuwi** [comment]
sorry...

**Comment by zulhiyatiuwi** [comment]
sorry...

**Pull request merged**
