### PR TITLE
Fix for Issue/2669 (resubmitted)

### PR DESCRIPTION
**Pull request by kest874**
This resolves https://github.com/osTicket/osTicket-1.8/issues/2669

### CODE REVIEW

**Comment by greezybacon** [comment]
Good catches. Thanks

**Comment by greezybacon** [comment]
I think 673e00d is the only fix that is required, right?

**Comment by greezybacon** [comment]
I cherry-picked 673e00d directly to `develop-next`. Thanks for the request

**Comment by protich** [comment]
@kest874 - Thanks again for the PR. Jared cherry-picked the commit of interest.

**Pull request closed without merging**
