### PR TITLE
Extended api

### PR DESCRIPTION
**Pull request by jaakkom**
Hi dudes,
I made extension to your api.

With my version you can:
-Search tickets
-Get Ticket data
-Get Thread Entry data
-Change status of ticket

I also made small change to ticket listing. In my version it shows both team and deparment. I think the dev switch for disabling autocron is necessary to prevent unwanted email readings, if using copy of live data on dev server.

What do you think about this changes?

screenshot from 2015-02-19 14 41 09

### CODE REVIEW

**Comment by ntozier** [comment]
I think that you increase the likely hood of your changes being added to core by separating the chnges into distinct pull requests.

i.e. the API changes into one pull request, and the "autocron dev switch" changes into a second pull request, and the "I also made small change to ticket listing. In my version it shows both team and deparment." into a third pull request.

**Comment by jaakkom** [comment]
I will do that. Should i fork dev-next or dev branch?
19.2.2015 17.23 kirjoitti "ntozier" <notifications@github.com>:

**Comment by jaakkom** [comment]
splitting to smaller parts

**Comment by Chefkeks** [comment]
@jaakkom 
Regarding the branch, I would say to develop ;)

**Pull request closed without merging**
