### PR TITLE
Dynamic form entry fields

### PR DESCRIPTION
**Pull request by protich**
Get all dynamic fields in DynamicFormEntry, not just fields with answers.

### CODE REVIEW

**Comment by greezybacon** [comment]
Looks like you pushed this branch to upstream. No biggie. Just delete the branch after the merge

**Comment by protich** [comment]
I wasn't paying attention -- new made.

**Comment by agstwn** [comment]
Hi protich,

sorry to bother you,
i think my question is not related to the topic.
i dont know how to ask you.


i wanna ask about,
statistic for staff..

can staff have statistic graph for his own account?

**Comment by ntozier** [comment]
@agstwn this seems off topic for this commit.
If you have a question you can as by starting a new issue, or posting on the forums at http://osticket.com/forum

**Pull request closed without merging**
