### PR TITLE
Stabilize osTicket v1.9-next

### PR DESCRIPTION
**Pull request by greezybacon**
### Outstanding
* [x] Ticket listing for search by user (followed from ticket-view) incorrect / incomplete
* [x] Teaching Karen to create outstanding issues
* [ ] Allow translations of the HTML hints
* [ ] Add a message to the "upload a new logo" widget, like:  `osTicket recommends a PNG logo with a size of about 380px by 64px and a transparent background` 
* [ ] Cascade dashboard statistics (for sub-departments)
* [ ] PJAX back navigation doesn't seem to work well
* [x] PJAX navigation from user directory breaks
* [ ] Verify layout for single and multi-lingual systems where multi-lingual content is displayed
* [ ] Dashboard statistics crash
* [x] Draft delete is broken
* [ ] Do something with FAQ view -> manage access link
* [x] Fix image paste+upload in Chrome
* [ ] Fix image annotate with S3 plugin
* [ ] When updating canned responses with attachments, saving changes causes white screen (line 53)
* [ ] Incorrect navigation after Ticket Delete
* [ ] Dress up search fields in advanced search (add ticket.user and ticket.user.organization)
* [x] `choose them` doesn't seem to work for the file upload utility
* [ ] Remove requirement to provide comments on assign and transfer
* [x] Consider role to view thread edit history
* [x] Auto expand context typeahead if clicking on arrow
* [x] Link dropdown in Redactor [insert link] modal is empty
* [ ] Deleting a form field after clearing the label field fails

### Lists
* [ ] Basic search does not work

### Collaborators
 * [ ] Update recipients and participants count on save

### UI
* [x] Add tooltip for attachment count and collaborator count in ticket queue
* [x] Cannot click to edit headline text in Redactor editor boxes
* [ ] Dialog dismiss and PJAX navigation should close variable typeahead
* [ ] When opening (clicking on in queue) tickets, it no longer auto-scrolls to the bottom or Reply box

### Database
* [ ] Relabel database patch versions
* [ ] `ticket.lastupdate` not set on upgrade
* [ ] Task permissions are not granted on upgrade
* [ ] `message` field not marked as externally stored
* [ ] Drop `%ticket__cdata` on upgrade (to force UTF8)

### i18n
* [ ] Drop `default_timezone_id` from language packs on Crowdin `config.yaml`
* [ ] Fix Redactor RTL plugin
* [x] Sorting secondary languages broken

### Tasks
* [x] Rebase
* [x] Add collaborators
* [ ] Send out emails
* [ ] Edit
* [ ] Print

### Forms
* [ ] Verify that password field still works when the field is required

### Advanced Search
* [ ] No feedback updating saved search
* [ ] Search for user by domain may not produce full results (i.e. DK #165018)
* [ ] Advanced search queue count incorrect; navigations to queue do not maintain correct results
* [ ] Hitting [Enter] in advanced search dialog does not submit the search

### CODE REVIEW

**Comment by Compilate** [comment]
Hello, I have a problem when the user make a new ticket and when I response a ticket. The problem is that the user not recieve the emails. I'm use a phpmail because my hosting is 1and1 and when i try to configure SMTP appears error. Is necesary use SMTP for response to email?. I sent test email from diagnostic is OK.

**Comment by ntozier** [comment]
Staff/Agent email responses are logged as internal notes.  They do not go to the Client/User  This is by design, not a problem or bug.

**Comment by Compilate** [comment]
Ahh ok,
 
Then when the Client/User open a new ticket, must be recieve a email with the
number ticket or the agent sent to client the number ticket with the other
methods?. Thanks.

**Comment by ntozier** [comment]
Unless you shut it off, yes they are sent an email with a link to the ticket.

**Comment by Compilate** [comment]
Thank you very much, the help has been very important for me.

**Pull request merged**
