### PR TITLE
Add agent's team tickets to My Tickets

### PR DESCRIPTION
**Pull request by protich**
My Tickets now includes ticket assigned to the agent directly as well as unassigned-tickets assigned to agent's teams (unassigned to any other agent).

Implements same logic for tasks.

### CODE REVIEW

**Comment by Chefkeks** [comment]
Would love to see ticket GROUPS (my tickets, my team xyz tickets, my team abc tickets, etc.) on the my ticket queue page for this.

What I mean with "ticket groups" is an option to group (not sort!) tickets so you see several collapse-able (sub)tables (groups) with the header being the value the user selected for grouping - under the my tickets page this would then be the assignment (agent itself, team xyz, team abc, etc.)

Hope you understand what I mean (otherwise I could do some mockups ;) )

**Comment by Chefkeks** [comment]
And no I don't mean custom queues, I mean groups of tickets under/at 1 ticket queue page :D

**Comment by protich** [comment]
@Chefkeks- I got what you meant. I think that still falls under custom queues feature --- just a sub-queue of My Tickets queue.

**Comment by Chefkeks** [comment]
Great!
So I think the custom queues will be a great enhancement :)

**Comment by protich** [comment]
This was reimplemented by Jared.

**Pull request closed without merging**
