### PR TITLE
lock: Implement lazy locking system

### PR DESCRIPTION
**Pull request by greezybacon**
This proposes a new, more flexible locking system, which waits to acquire a lock until the user starts entering information into the system, or performing an action which immediately requires a lock. Under this scheme, simply viewing a lockable object, such as a ticket, does not require a lock; however, starting to type a response to the end user will trigger a lock acquisition. If a lock cannot be acquired, the user is notified with an annoying warning banner.

### Outstanding
* [x] Fix double AJAX posting

##### New slide out "message bar" with error instead of the annoying popup
screen shot 2015-07-29 at 4 00 34 pm

### CODE REVIEW

**Comment by jdelhome3578** [comment]
:+1:

**Comment by Chefkeks** [comment]
That's a really neat improvement :+1:

**Comment by jdelhome3578** [comment]
As soon as I start typing a response the `Your lock is expiring soon.` message drops down. I click on `renew` and it just spins. Is this the intended operation?

**Comment by greezybacon** [comment]
> As soon as I start typing a response the Your lock is expiring soon. message drops down. I click on renew and it just spins. Is this the intended operation?

Maybe you mis-patched something? Are there any notable javascript logs?

**Comment by jdelhome3578** [comment]
I retested from the tip and I am still having issues #2343

**Pull request merged**
