### PR TITLE
Fixed typo in include/staff/staff.inc.php

### PR DESCRIPTION
**Pull request by ebell451**
Fixed typo

### CODE REVIEW

**Comment by greezybacon** [comment]
I'll chery-pick your commit. Thanks for it. In the future, please submit requests from separate branches (the Edit feature of GitHub does this automatically), so that unrelated stuff like the merge of osTicket/develop is not included in the request

**Comment by protich** [comment]
@greezybacon -- Cherry picked commit merged directly?

**Comment by greezybacon** [comment]
Cherry-picked into `develop`

**Comment by ebell451** [comment]
My apologies for the inconvenience. I was trying to be helpful, but also still learning GitHub.

**Comment by greezybacon** [comment]
@ebell451 no worries. You were helpful, and I merged the first of your commits into the develop branch

**Pull request closed without merging**
