### PR TITLE
kb: Add setting to enable only for authenticated clients

### PR DESCRIPTION
**Pull request by greezybacon**
screen shot 2015-03-17 at 11 39 01 am

### CODE REVIEW

**Comment by Chefkeks** [comment]
I guess this will make a lot of osTicket admins happy ;)
:+1:

**Comment by robintoy** [comment]
What would be great is if you could enable that but then turn this on for certain topics and not for others.

For instance we have a spam filering system called "SpamSnake" which would be nice to keep KBs in-house to registered users / clients and not public where base Outlook issues we do not mind anyone accessing.

**Comment by greezybacon** [comment]
@robintoy I'm trying to avoid a more sophisticated ACL tool for the moment. I think long term we need the ACL option though

**Comment by robintoy** [comment]
Hi @greezybacon , its good to know it is on the cards but yes you have to start somewhere. Been looking at some of the other pulls and looks like an ACL is needed for a lot of them.

**Pull request merged**
