### PR TITLE
logo: Allow customized SCP logo

### PR DESCRIPTION
**Pull request by greezybacon**
This patch adds the ability for administrators to customize the logo shown in the staff control panel

### Outstanding
  * [ ] Add a message to the "upload a new logo" widget, like:
    ```
osTicket recommends a PNG logo with a size of about 380px by 64px and a transparent background
```

### Screenshots
screen shot 2015-02-05 at 5 47 53 pm

screen shot 2015-02-05 at 5 47 59 pm

screen shot 2015-02-05 at 6 01 32 pm

### CODE REVIEW

**Comment by Chefkeks** [comment]
Nice :+1:

**Comment by Chefkeks** [comment]
@greezybacon 
The new logo looks like 2015 design language which is good, but unfortunately 2 things I personally do not like at it:
1. the kangaroo looks not so dynamic and a little (little, little) bit crippled
2. don't like the orange color in the "o" and "s" of "osTicket"

**Comment by sstillwell** [comment]
Awesome - saves me from having to re-replace the logo every time I update.  Bravo, gents!  Now, if we could do the same for the SCP login-background.jpg... :)  The kangaroos are nicely done, but I'd prefer to do just a straight gradient.

**Comment by ebell451** [comment]
I agree with @sstillwell this saves me time after updating as well as the login-background.jpg. Those are two of the modifications I make after each update. So thanks again for this added feature.

**Comment by greezybacon** [comment]
@sstillwell @ebell451 If that's your greatest concern for future releases, I gather we're doing a pretty good job

**Comment by ebell451** [comment]
@greezybacon I wouldn't say that is my *greatest* concern; however, it is something that I modify on each update so is very helpful...and, you all are doing a pretty good job. Keep up the good work.

**Comment by sstillwell** [comment]
@greezybacon well, you ARE doing a good job, but now that you mention it... *goes off to enter another issue...*

:)

**Comment by turorit** [comment]
Thankyou :) one less tweak to do after each upgrade :)
Its the little things that count!

**Comment by balojs** [comment]
:+1:

**Comment by balojs** [comment]
@greezybacon this includes the logo for print? 
osticket/include/fpdf/print-logo.png 

Thanks

**Comment by greezybacon** [comment]
@balojs that's a good questions. I believe it only uses the client side logo as currently implemented.

**Pull request merged**
