### PR TITLE
Feature/custom queues

### PR DESCRIPTION
**Pull request by lewisburgess**

### CODE REVIEW

**Comment by greezybacon** [comment]
What is this about? You're duplicating pull request #2577

**Comment by lewisburgess** [comment]
Hi, really sorry - new to GitHub! I’m trying to grab the latest development
release for 1.10 (post RC2) and your custom ticket queue together.

I’ve been playing with RC2 and really like it, but wanted to use the custom
ticket queue fork of yours. Unfortunately this went wrong - css errors and
other functions failing, so had to install fresh and since there have been
loads of changes since RC2 was released thought it best to grab all the
changes too.

I’m leaning how GitHub works as the concept is quite new I’m stumbling
around a bit - the Windows Git app is breaking the files causing a core:
invalid schema signature error.

Best wishes,

Lewis.

**Comment by greezybacon** [comment]
@lewisburgess totally understand. I've tried teaching Git using the Github app before. It's very confusing. The command line git tools are much easier to understand and navigate. Good luck!

Open up an issue if you run into problems or questions.

**Comment by lewisburgess** [comment]
Cool, thanks Jared.

I’m assuming I can merge osTicket/develop-next (last updated 3 days ago)
with your /feature-customqueue ?

Thanks.

**Comment by greezybacon** [comment]
Yeah. For experimental testing, that would likely be the easiest. I will likely rebase in the next few days.

**Pull request closed without merging**
