### PR TITLE
csrf: Fix CRSF violation on client login

### LINKED ISSUE #2276: 1.10 rc1 : client login does not work
first Login works (with "create account" and then direkt link from email) 
but then after logout, a Login isn't possible:
"Valid CSRF Token Required"

### LINKED ISSUE #2287: 1.10 RC1 Issue Open new ticket
If I try to open a new ticket at frontend, there is after some seconds a popup I have to restore the page. I have to click ok 100 times to write again. 3 seconds later the same popup.

Log shows (5000 entries): 
Ungültiger CSRF-Token __CSRFToken__

Ungültiger CSRF-Token [8f6c258bd40d94df886ea19b8aa8edffc75f4d5e] bei http://www.service.192.168.1.35.xip.io/ajax.php/draft/2173
Log-Datum: Freitag, 24. Juli 2015 11:05 IP-Adresse: 92.xxx.xxx.xxx

### PR DESCRIPTION
**Pull request by greezybacon**
Fixes #2276 
Fixes #2287

### CODE REVIEW

**Comment by bdgr87** [comment]
Hello,

I will try it here I already at a topic regarding this issue at http://osticket.com/forum/discussion/comment/97787#Comment_97787

I changed the files that you mentioned. But when I change the login.php I just get a blank page. If I leave it how it was originally. Than I get Valid CSRF Token Required

**Comment by ntozier** [comment]
Sounds like you didnt do something right then.  Since you are getting a blank page please consult your PHP error log and let us know the error that you are getting.

**Comment by bdgr87** [comment]
Here it is

[Wed Jul 29 09:02:34.022841 2015] [mpm_prefork:notice] [pid 863] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Jul 29 09:02:35.098468 2015] [suexec:notice] [pid 2299] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 29 09:02:35.117085 2015] [auth_digest:notice] [pid 2299] AH01757: generating secret for digest authentication ...
[Wed Jul 29 09:02:35.117566 2015] [lbmethod_heartbeat:notice] [pid 2299] AH02282: No slotmem from mod_heartmonitor
[Wed Jul 29 09:02:35.135380 2015] [mpm_prefork:notice] [pid 2299] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Wed Jul 29 09:02:35.135424 2015] [core:notice] [pid 2299] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by ntozier** [comment]
That does not look like a PHP error log, it does look like an Apache log.

**Comment by gmt-it** [comment]
Latest Develop-next shows the error again while creating a ticket at client interface. Do you forgot to include the CSRF changes at secure.inc.php? 

<pre>
/*********************************************************************
    secure.inc.php

    File included on every client's "secure" pages

    Peter Rotich <peter@osticket.com>
    Copyright (c)  2006-2013 osTicket
    http://www.osticket.com

    Released under the GNU General Public License WITHOUT ANY WARRANTY.
    See LICENSE.TXT for details.

    vim: expandtab sw=4 ts=4 sts=4:
**********************************************************************/
if(!strcasecmp(basename($_SERVER['SCRIPT_NAME']),basename(__FILE__))) die('Kwaheri!');
if(!file_exists('client.inc.php')) die('Fatal Error.');
require_once('client.inc.php');

/******* CSRF Protectin *************/ 
// Enforce CSRF protection for POSTS 
 if ($_POST  && !$ost->checkCSRFToken()) { 
     Http::redirect('index.php'); 
     //just incase redirect fails 
     die('Action denied (400)!'); 
} 

//Client Login page: Ajax interface can pre-declare the function to trap logins.
if(!function_exists('clientLoginPage')) {
    function clientLoginPage($msg ='') {
        global $ost, $cfg, $nav;
        $_SESSION['_client']['auth']['dest'] =
            '/' . ltrim($_SERVER['REQUEST_URI'], '/');
        require('./login.php');
        exit;
    }
}

//User must be logged in!
if(!$thisclient || !$thisclient->getId() || !$thisclient->isValid()){
    clientLoginPage();
    exit;
}
$thisclient->refreshSession();
?>
</pre>

**Comment by greezybacon** [comment]
No, the CSRF code should be removed from secure.inc.php.

Am Samstag, 1. August 2015 schrieb gmt-it :

**Comment by gmt-it** [comment]
@greezybacon Hmm. With CSRF Protection in it there is no problem to write new tickets. Without the code I got 1000nds of CSRF errors in log and there is no chance to write at the edit area....

**Comment by greezybacon** [comment]
I can't reproduce your issue the tip of #2056 works just fine

**Comment by gmt-it** [comment]
@greezybacon Just installed the latest develop-next from zip file. The login error is back: Agents can not login because of: 

Ungültiger CSRF-Token __CSRFToken__

Ungültiger CSRF-Token [f0b79765d727bcc164802fbd3b53dfc97f7f78c1] bei http://www.dev-next.192.168.1.35.xip.io/scp/login.php
Log-Datum: Mittwoch, 5. August 2015 10:58 IP-Adresse: 192.168.1.66

Only way to login is to exclude CRSF code from /scp/login.php.

**Comment by mfelber** [comment]
I only have randomly this error, I'm using the latest develop-next files too. In my cases it occurs when after the browser url ../scp/ something follows: for example /scp/login.php or /scp/logout.php?auth=5ff7a2a55bb0782bc1ca27bce26920c6 (like after the logout). When I remove everything after ../scp/ make a page refresh and then try to login again the CSFR-Token error doesn't occur..

**Pull request merged**
