### PR TITLE
Feature :: Access Control 2.0

### PR DESCRIPTION
**Pull request by greezybacon**
This implements the mockups in #2096. For context and questions about how this works, please see the other issue.

### Features
* [x] Remove Groups- Change to Roles
* [x] Add ability to add agents to Teams from the Team listing 
* [x] Remove Signature box from Agent configurations page
* [x] Create Permissions tab to determine the agent's primary permissions (role) of the help desk
* [x] Create Department tab on Agent Configurations page; determine departments they can access and with what permissions (roles) they have with each department if different from their default role. 
* [x] Primary Department with Primary Roles would be listed first with a "+" to add additional departments the Agent can access. As departments are added, the role of that Agent for that department will be configured in the drop down of existing roles of the help desk or a new role can be created 
* [x] Create Flag field for Alerts & Notices per department, per agent on a local level
* [x] Ability to clone or copy existing roles in Help Desk

### Outstanding
* [x] Upgrade patch for new database fields
* [x] Make colored button usage consistent
* [x] Remove addition of `— Select xxx —` via quick add
* [x] Set password for new agent (via full page add)
* [x] Departments and teams failed to install
* [x] Add closed date field to task table

##### Agent listing with dropdowns for actions and new consistent buttons, sporting new colors
screen shot 2015-07-06 at 4 10 44 pm

##### Clean look for the agent management page, including tabs for lowered complexity
screen shot 2015-07-06 at 4 11 01 pm

##### Popup dialog for set password and associated options
screen shot 2015-07-06 at 4 11 12 pm

##### Agent access is configured directly, rather than via the "Group" (which is retired)
screen shot 2015-07-06 at 4 11 20 pm

##### Quick-add via popup dialog for departments (and other access control pieces)
screen shot 2015-07-06 at 4 11 33 pm

##### Permission for global things such as user directory are configurable in the agent settings
screen shot 2015-07-06 at 4 11 46 pm

##### Teams are also configured in the agent settings
screen shot 2015-07-06 at 4 12 44 pm

##### And quick-add team option is available too
screen shot 2015-07-06 at 4 12 57 pm

##### Furthermore, agents can be added directly to the team, alerts for each team member are optional now
screen shot 2015-07-06 at 4 13 12 pm

##### Even via quick-add popup
screen shot 2015-07-06 at 4 13 23 pm

##### Department members can be added to the department, alerts for extended members are optional per each member
screen shot 2015-07-06 at 4 13 48 pm

##### Sorting options moves to a search drawer *to make room for more features*
screen shot 2015-07-06 at 4 20 52 pm

##### Revised "Profile" page sports tabs for easier editing, perhaps multiple signatures could find a place in the interface now
screen shot 2015-07-06 at 4 21 59 pm

### CODE REVIEW

**Comment by harrisyn** [comment]
Can this be merged with 1.9.9 or 1.10?

**Comment by protich** [comment]
:+1:  :100:  :100:

**Comment by greezybacon** [comment]
@harrisyn this will debut in v1.10

**Comment by balojs** [comment]
+1

**Comment by mfelber** [comment]
Looks awesome :clap:

**Comment by markus4000** [comment]
Request;
+Agent should be able to set his flag "on holiday" by himself.
+Agent should be able to define a deputy that gets the mails in case that he is on holidays.

**Comment by ntozier** [comment]
@markus4000 I feel like that should probably be a separate request.

also re: "+Agent should be able to define a deputy that gets the mails in case that he is on holidays."
I personally think that tickets shouldn't be able to be assigned to an Agent who is on holiday which means that this wouldn't be needed since they wouldn't have any tickets assigned to them.

**Comment by harrisyn** [comment]
Except that the agent may already have open tickets

**Comment by ntozier** [comment]
@harrisyn the system should prompt to re-assign tickets when Holiday mode is triggered, or un-assign them (at Admins configuration option)

**Comment by markus4000** [comment]
@ntozier: They can have unsolved tickets, where they are waiting for a response.

**Pull request merged**
