### PR TITLE
forms: Add ability to delete properties form

### PR DESCRIPTION
**Pull request by protich**
This adds ability to delete form properties on list deletion.

### CODE REVIEW

**Comment by protich** [comment]
TODO: We cannot assume a dynamic entry/answer has  an associated form.

**Comment by Chefkeks** [comment]
I am not so deep into the code, so stupidly asking the following:
Does it fix https://github.com/osTicket/osTicket-1.8/issues/1018 ?

If so, you should may consider also a database cleanup / upgrade patch to delete orphaned data which is still in the database. If not, sorry as said not so deep into the code, sometimes I can read what a PR will do sometimes I am struggling with reading the code ;)

**Comment by greezybacon** [comment]
@Chefkeks the dynamic forms code is the most abstract code in the system. This code specifically disconnects fields from their form when the form is deleted. Except for custom list deletions, which will cause the fields of the properties to actually be deleted. Unfortunately, the inability to drop a custom list is still outstanding.

**Comment by Chefkeks** [comment]
@greezybacon 
Thanks for the explanation :)

**Comment by greezybacon** [comment]
@protich rebase required

**Comment by protich** [comment]
Rebased on top of develop-next

**Pull request merged**
