### PR TITLE
Issue/ui consistency

### PR DESCRIPTION
**Pull request by nfebuary**
Apply the new look and feel to all the pages in the Agent and Admin interface.

### CODE REVIEW

**Comment by ntozier** [comment]
*COUGH*screenshots

**Comment by Chefkeks** [comment]
> COUGHscreenshots

:+1:

**Comment by nfebuary** [comment]
Pull-right may have been deleted.

**Comment by greezybacon** [comment]
This is rebased in #2426 (again, without screenshots)

**Pull request closed without merging**
