### PR TITLE
ui: malformed featured FAQ URL in sidebar

### LINKED ISSUE #2364: 1.10 RC1 Issues - Featured Questions URL
`http://kb/faq.php?id=1` is missing osticket root

image

### PR DESCRIPTION
**Pull request by jdelhome3578**
Fixes #2364

### CODE REVIEW

**Comment by greezybacon** [comment]
According to `bootstrap.php`, line 337, `ROOT_PATH` should already have a trailing slash. Are you defining it in your config file?
```php
// Determine the path in the URI used as the base of the osTicket
// installation
if (!defined('ROOT_PATH') && ($rp = osTicket::get_root_path(dirname(__file__))))
    define('ROOT_PATH', rtrim($rp, '/').'/');
```

**Comment by jdelhome3578** [comment]
I am removing the extra `/` from the code compared to other references and it fixed the issue with only this section.

**Comment by greezybacon** [comment]
I'm not sure what you mean. What fixed the issue?

**Comment by jdelhome3578** [comment]
`-            <div><a href="<?php echo ROOT_PATH; ?>/kb/faq.php?id=<?php`
`+            <div><a href="<?php echo ROOT_PATH; ?>kb/faq.php?id=<?php`

**Comment by greezybacon** [comment]
Yup. You're right

**Pull request merged**
