### PR TITLE
Form style browser fix.

### PR DESCRIPTION
**Pull request by nfebuary**
Firefox display issue.

### CODE REVIEW

**Comment by greezybacon** [comment]
You've *got* to work on your pull request descriptions

**Comment by nfebuary** [comment]
Sorry, I'll get better at it. I wasn't really sure what to put.

**Comment by ntozier** [comment]
Describe to me in three-four sentences what this pull request does. :)

**Comment by nfebuary** [comment]
Merges redundant CSS into one rule and adds consistent look and feel for cross browser display of form text fields, select lists and search fields. :dancers: :)

**Comment by ntozier** [comment]
That's your pull request description.  :)

**Comment by greezybacon** [comment]
:+1:

**Comment by nfebuary** [comment]
See, you can teach a designer new tricks. ;)

**Comment by ntozier** [comment]
'sit, ubu, sit. good dog'  :)

**Comment by nfebuary** [comment]
woof! ;)

**Comment by Chefkeks** [comment]
:D :D :D :+1:

**Pull request merged**
