### PR TITLE
Resolved issue #2835 - cfg made global.

### PR DESCRIPTION
**Pull request by A-Lawrence**

### CODE REVIEW

**Comment by greezybacon** [comment]
Thanks for the find and fix

**Comment by Korrosivo** [comment]
@GoodbyeWorld This fix isn't merged yet on develop-next branch. You must wait until someone merge the PR :smile:

**Comment by GoodbyeWorld** [comment]
@Korrosivo Thanks, that makes sense!

**Comment by greezybacon** [comment]
Thanks for the code. @protich included this in #2844

**Pull request closed without merging**
