### PR TITLE
Add concept of variable typeahead in templates

### PR DESCRIPTION
**Pull request by greezybacon**
This feature adds popup typeahead when editing email templates. This is done in hopes of eliminating the inconsistent and incomplete documentation surrounding the templating feature as a whole

### Outstanding
  * [x] Internationalize all the variable descriptions
  * [x] Add typeahead to access templates
  * [ ] Add typeahead to textboxes for subject lines
  * [x] Add typeahead to thank you pages
  * [x] Add context validation error messages on update
  * [ ] Retire the [Supported Variables] pop out
  * [ ] Consider RTL rendering
  * [x] Make suggestions scrollable (as opposed to limited)
  * [x] Support include attachments with `%{message.files}`
  * [x] Add context to "Send Email" filter action

### Screenshots
screen shot 2015-04-18 at 10 41 23 am
screen shot 2015-04-18 at 10 42 00 am

##### Custom data is also welcomed
screen shot 2015-04-18 at 10 43 18 am

##### Root context is also exposed
screen shot 2015-04-18 at 10 50 01 am

##### Dates are now localizable to the recipient's time zone and locale
screen shot 2015-04-20 at 4 32 58 pm

### CODE REVIEW

**Comment by Chefkeks** [comment]
WOW! That's huge!
This will revolutionize the variable usage!

Really nice enhancement! :+1:
Keep up the good work!

**Comment by greezybacon** [comment]
@Chefkeks I know. I'm so excited about this one!

**Comment by voarsh** [comment]
:+1:

**Comment by greezybacon** [comment]
I feel like `%{message.attachments}` is better than `%{message.files}`; however, ThreadEntry::getAttachments seems to be in use already and masks the variable replacer function getVar. Perhaps we should call `getVar('attachments')` first before attempting to call `getAttachments()`

**Pull request merged**
