### PR TITLE
bug: Collaborators Notice

### PR DESCRIPTION
**Pull request by protich**
Fix case where collaborators were not being notified 
Alert admin last on new ticket - just in case admin email address is also used by an alerted agent.

### CODE REVIEW

**Comment by greezybacon** [comment]
What's up with the `$charset` hinting in mail parse? Isn't UTF-8 the default?

**Comment by protich** [comment]
``parseAddressList`` gets called statically in ``getAllEmailRecipients`` -- meaning ``$this`` won't be in valid context.

**Comment by greezybacon** [comment]
That makes sense. Looks good

**Comment by greezybacon** [comment]
This was merged with #2549

**Pull request closed without merging**
